# 项目相关配置
SFS:
  name: Science Fiction Server
  version: 1.0.8

server:
  # 服务器HTTP端口，默认为80
  port: 80
  servlet:
    # 应用访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/science_fiction
    username: test
    password: "test"
  servlet:
    multipart:
      max-file-size: 10MB
mybatis:
  mapper-locations: classpath*:com/veeja/mapper/*.xml
  type-aliases-package: com.veeja.pojo
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl