spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://81.70.142.228:3306/science_fiction
    username: liuweijia
    password: "0000"
  servlet:
    multipart:
      max-file-size: 10MB
mybatis:
  mapper-locations: classpath*:com/veeja/mapper/*.xml
  type-aliases-package: com.veeja.pojo
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080